# Site settings
title: Xmartlabs Blog
email: getintouch@xmartlabs.com
address: Dr Mario Cassinoni 1011 - 11200
phone_eeuu: +16506141829
phone_uruguay: (+598) 2408 7915
description: > # this means to ignore newlines until "baseurl:"
  Articles by Xmartlabs, sharing the knowledge about full-stack mobile design and development in iOS, Android and Ruby.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://xmartlabs.com" # the base hostname & protocol for your site
url_team: "https://xmartlabs.com/#our_team"
url_blog: "https://blog.xmartlabs.com"
twitter_username: xmartlabs
github_username: xmartlabs

# Build settings
markdown: kramdown
future: false
timezone: America/Montevideo
permalink: /:year/:month/:day/:title/

plugins: [jekyll-paginate-v2]

plugins_dir:
  - jekyll-paginate-v2

# Pagination Settings
pagination:
  enabled: true
  per_page: 12
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

defaults:
  # Default layout and language to everything
  -
    values:
      layout: "default"
  # Specify default pagesâ€™ layout
  -
    scope:
      path: "_posts/martin"
      type: "posts"
    values:
      author: "mtnBarreto"

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
